account/urls.py
from django.urls import path
from account import views

app_name = 'account'

urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name="login"),
    path('logout/', views.LogoutUserView.as_view(), name="logout"),
]

poll/urls.py
from django.urls import path
from poll import views

app_name = 'poll'

urlpatterns = [
    path('index/', views.IndexView.as_view(), name="index"),
]

pollpr/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('poll/', include('poll.urls')),
    path('account/', include('account.urls')),
    path('api-auth/', include('rest_framework.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root =settings.STATIC_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Account(models.Model):
    photo = models.ImageField(upload_to="accountphotos", blank=True, null=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="account")
    cor_uns_number = models.IntegerField(default=0)
    uncur_uns_number = models.IntegerField(default=0)

    class Meta:
        verbose_name = "Account"
        verbose_name_plural = "Accounts"

    def __str__(self):
        return self.user.username    
    

poll/models.py
from django.db import models

# Create your models here.

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class QuestionModel(models.Model):
    name = models.CharField(max_length=1000)
 
    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"

    def __str__(self):
        return self.name    


class ChoiceModel(models.Model):
    name = models.CharField(max_length=1000)
    is_true = models.BooleanField()
    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE, related_name="question_answers")
    
    class Meta:
        verbose_name = "Choice"
        verbose_name_plural = "Choices"

    def __str__(self):
        return self.question.name + "|" + self.name   


class PollModel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_polls")
    question = models.ForeignKey(QuestionModel, on_delete=models.CASCADE, related_name="question_polls")
    answer = models.ForeignKey(ChoiceModel, on_delete=models.CASCADE, related_name="choice_polls")

    class Meta:
        verbose_name = "Poll"
        verbose_name_plural = "Polls"

    def __str__(self):
        return self.user.username + "|" + self.question.name + "|" + self.answer.name
    

account/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.views import generic
from django.contrib.auth.models import User
import re
from django.contrib import messages
from account.models import Account
from django.contrib.auth import authenticate, login, logout
# Create your views here.

import re
def check_password(password_):
    if (len(password_)>5 and re.search("[0-9]", password_) and
        (re.search("[a-z]", password_) or re.search('[A-Z]', password_))):
        return True
    else:
        return False


class RegisterView(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request, 'register.html')
    
    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            if User.objects.filter(username=username):
                messages.info(request, "Please enter another username")
            elif not check_password(password):
                messages.info(request, "password must contain letters and numbers, minimum length must be 6 characters" )
            else:
                user = User.objects.create_user(username=username, password=password)
                Account.objects.create(user=user)
                messages.success(request, "user created")

                login(request, user)
                return redirect("poll:index")

        if not username:
            messages.info(request, 'Please, enter username')
        if not password:
            messages.info(request, "Please, enter password")        

        return redirect('account:register')


class LoginUserView(generic.View):
    def get(self, request, *args, **kwargs):
        return render(request, 'login.html')
    
    def post(self, request, *args, **kwargs):
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("poll:index")
        else:
            messages.info(request, "user was not found")
            return redirect('account:login')


class LogoutUserView(generic.View):
    def get(self, request, *args, **kwargs):
        logout(request)        
        return redirect("poll:index")

poll/views.py
from django.shortcuts import render, HttpResponse, redirect, get_list_or_404
from django.views import generic
from poll.models import QuestionModel, ChoiceModel, PollModel
from account.models import Account
from django.contrib import messages
from django.contrib.auth.models import User

# Create your views here.

class IndexView(generic.View):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            questions = QuestionModel.objects.all()
            
            context = {
                "questions": questions,
            }
            return render(request, "index.html", context)
            
        return render(request, "index.html")
    
    
    def post(self, request, *args, **kwargs):
        question_ids = []
        answer_ids = []
        print(request.POST)

        for i in request.POST:
            if i.startswith('question'):
                question_ids.append(request.POST[i])
            elif i.startswith('answer'):
                answer_ids.append(request.POST[i])

        print(question_ids, answer_ids)


        for i in range(len(answer_ids)):
            # question = QuestionModel.objects.get(id=question_ids[i])
            # print(question)
            answer = ChoiceModel.objects.get(id=answer_ids[i])
            question = answer.question
            print(answer)
            print(question)

        
            if request.user.is_authenticated:
                PollModel.objects.create(user = request.user, question = question, answer = answer)
                user = User.objects.get(username = request.user.username)
                account_user = Account.objects.get(user = user)

                if answer.is_true == True:
                    account_user.cor_uns_number += 1
                    account_user.save()
                else:
                    account_user.uncur_uns_number += 1
                    account_user.save()  
            
        return redirect("poll:index")
    

templates/components/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block head %} {% endblock %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <body>
    
    {% include 'components/navbar.html' %}
    {% block content %} {% endblock %}
    {% include 'components/footer.html' %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
  </body>
</html>

templates/components/navbar.html
<nav class="navbar" style="background-color: #cf0d8eaf;">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'poll:index' %}">POLL Home Page</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end" style="background-color: #bb20c9;" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">SEARCH</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Profil
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="">{{request.user.username}}</a></li>
              {% if request.user.is_authenticated %}
              <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
              {% else %}
              <li><a class="dropdown-item" href="{% url 'account:login' %}">Login</a></li>
              <li><a class="dropdown-item" href="{% url 'account:register' %}">Register</a></li>
              {% endif %} 
              <li>
                <hr class="dropdown-divider">
              </li>
              
            </ul>
          </li>
        </ul>
        <form class="d-flex mt-3" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </div>
</nav>

templates/index.html
{% extends 'components/base.html' %}

{% block head %}<title>Index Page</title> {% endblock %}


{% block content %}
{% if not request.user.username %}
<div class="container mt-5"> 
    <nav class="navbar  rounded-3"  style="background-color: #8ad1d1af; width:760px;">
        <div class="container mt-5">        
    <h5><p>Sualların təqdim olunması üçün <a href="{% url 'account:login' %}"><b>profil</b></a>  hesabıniza daxil və ya <a href="{% url 'account:register' %}"><b>qeydiyyatdan</b></a> keçin</p></h5>
    </nav>    
        </div>
    </div>
{% endif %}     
{% if request.user.is_authenticated %}
<div class="container mt-3">
    <div class="card">
        <div class="card-body">
            
            <form method="POST">
            {% csrf_token %}
            {% for question in questions %} 
            {{question}}
            <input class="form-check-input" type="hidden" name="question_id{{question.id}}"  value="{{question.id}}">  
            {% for question_answer in question.question_answers.all %}   
            <div >
                
                <input class="form-check-input" type="radio" name="answer_id{{question.id}}"  value="{{question_answer.id}}">
                <label class="form-check-label" for="answer_id{{question.id}}">{{question_answer.name}}</label>
            </div>
            {% endfor %}
            <p>{{ Message }}</p>
            {% endfor %}
            
            <button class=" btn btn-primary" type="submit">Confirm</button>
            
            </form>
            
            <!-- <div class="form-check">
                <input class="form-check-input" type="radio" name="flexRadioDefault" id="flexRadioDefault2" checked>
                <label class="form-check-label" for="flexRadioDefault2">Default checked radio</label>
            </div>     -->
        </div>        
    </div>
</div>
{% endif %}

{% endblock %}

templates/login.html
{% extends 'components/base.html' %}

{% block head %} <title>Login Page</title> {% endblock %}


{% block content %}

<div class="container mt-3">
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        <label for = "username">Username</label><br>
        <input type="text" style="width:30%" name="username" id="username"><br><br>
        <label for="password">Password</label><br>
        <input type="text" style="width:30%"  name="password" id="password"><br><br>
        <button class="btn btn-primary" type="submit">Login</button>

    </form>

    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div>



{% endblock %}

templates/register.html
{% extends 'components/base.html' %}

{% block head %}<title>Register Page</title> {% endblock %}

{% block content %}

<div class="container mt-3">
    <h1>Register</h1>
    <form method="POST">
        {% csrf_token %}
        <label for = "username">Username</label><br>
        <input type="text" style="width:30%" name="username" id="username"><br><br>
        <label for="password">Password</label><br>
        <input type="text" style="width:30%"  name="password" id="password"><br><br>
        <button class="btn btn-primary" type="submit">Register</button>

    </form>

    {% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

</div>



{% endblock %}